export { default as corePostCreate } from './corePostCreate'
export { default as corePostDelete } from './corePostDelete'
export { default as corePostGet } from './corePostGet'
export { default as corePostGetRandom } from './corePostGetRandom'
export { default as corePostUpdate } from './corePostUpdate'
